# Generated by Django 5.1.2 on 2024-11-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_custom_user_user_type_jobseekerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('jobSeeker', 'JobSeeker')], max_length=20),
        ),
    ]
