# Generated by Django 5.1.2 on 2024-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_custom_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='upload_cv',
            field=models.FileField(blank=True, null=True, upload_to='cv_uploads/'),
        ),
    ]
