# Generated by Django 5.1.2 on 2024-11-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobseekerprofile_upload_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile_pic'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='Media/Profile_pic'),
        ),
    ]
