# Generated by Django 5.1.2 on 2024-11-04 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_custom_user_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security')], max_length=100, null=True)),
                ('category', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time')], max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('openings', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('Job_Image', models.ImageField(null=True, upload_to='Media/Job_Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
