# Generated by Django 5.1.2 on 2024-11-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_jobapplymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='jobseeker_skill',
            field=models.CharField(choices=[('programming', 'Programming'), ('networking', 'Networking'), ('graphics_design', 'Graphics Design'), ('cyber_security', 'Cyber Security')], max_length=20),
        ),
    ]
